<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-3G0BE48" failures="1" tests="5" name="runner.TestRunner" time="68.233" errors="0" timestamp="2021-10-10T15:55:51 EET" skipped="0">
  <testcase classname="runner.TestRunner" name="runScenario" time="7.191"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="6.565"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="7.724"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="42.389">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at steps.E2ETests.moves_to_checkout_cart_and_enter_personal_information_on_checkout_page_and_place_the_order(E2ETests.java:50)
at âœ½.Moves to checkout cart and enter personal information on checkout page and place the order(file:///E:/myworkspaceclipse/TAF/src/test/java/features/EndToEnd_Tests.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.364"/>
  <system-out/>
</testsuite> <!-- runner.TestRunner -->
